# Generated by Django 5.2.3 on 2025-11-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="data_proximo_contato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Próximo Contato"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="observacao_interna",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observação Interna"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="origem",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("indicacao", "Indicação"),
                    ("google", "Google"),
                    ("organico", "Orgânico"),
                    ("evento", "Evento"),
                ],
                default="organico",
                max_length=20,
                verbose_name="Origem do Lead",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="prioridade",
            field=models.CharField(
                choices=[("baixa", "Baixa"), ("media", "Média"), ("alta", "Alta")],
                default="media",
                max_length=10,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="probabilidade_fechamento",
            field=models.IntegerField(
                default=0,
                help_text="0-100",
                verbose_name="Probabilidade de Fechamento (%)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="valor_curso",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor do Curso",
            ),
        ),
    ]
